import type { Project } from "@/types/project";

const now = "2026-05-31T00:00:00.000Z";

export const projects: Project[] = [
  {
    id: "project_2bhk_calm_refresh",
    title: "Calm 2BHK Interior Refresh",
    slug: "calm-2bhk-interior-refresh",
    city: "Gomti Nagar",
    serviceType: "Interior Painting",
    propertyType: "Apartment",
    shortDescription: "Sample project presentation for a 2BHK refresh with washable neutral walls and a softer bedroom palette.",
    problem: "The apartment had uneven old paint, nail marks, and dull living room walls that made the space feel smaller.",
    solution:
      "Wallora planned a full interior repaint with surface correction, primer, washable finish paint, and a warmer neutral palette for common areas.",
    resultSummary: "The home felt brighter, cleaner, and ready for move-in within four working days.",
    timeline: "4 days",
    areaSize: 960,
    budgetRange: "Rs. 42,000 - Rs. 58,000",
    materialsUsed: ["Acrylic wall putty touch-ups", "Interior primer", "Washable emulsion", "Masking and floor protection"],
    beforeImages: [{ src: "/images/projects/calm-2bhk-before-1.jpg", alt: "Old living room wall before repaint", tone: "mist" }],
    afterImages: [{ src: "/images/projects/calm-2bhk-after-1.jpg", alt: "Fresh neutral living room after repaint", tone: "warm" }],
    galleryImages: [
      { src: "/images/projects/calm-2bhk-gallery-1.jpg", alt: "Neutral living room finish", tone: "warm" },
      { src: "/images/projects/calm-2bhk-gallery-2.jpg", alt: "Bedroom soft paint finish", tone: "sage" },
      { src: "/images/projects/calm-2bhk-gallery-3.jpg", alt: "Protected floor during painting", tone: "mist" },
    ],
    featured: true,
    tags: ["Interior", "Apartment", "Neutral Palette"],
    relatedServiceSlug: "interior-painting",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project_monsoon_waterproofing_pune",
    title: "Monsoon Waterproofing Rescue",
    slug: "monsoon-waterproofing-rescue",
    city: "Alambagh",
    serviceType: "Waterproofing",
    propertyType: "Independent House",
    shortDescription: "Sample waterproofing plan for recurring seepage before repainting an exterior-facing bedroom wall.",
    problem: "The wall showed bubbling paint and damp patches every monsoon because the moisture source was untreated.",
    solution:
      "The team inspected the affected zone, prepared the surface, applied waterproofing treatment, and planned repainting after curing.",
    resultSummary: "The wall was stabilized for repainting and the customer received clear curing guidance.",
    timeline: "5 days",
    areaSize: 420,
    budgetRange: "Rs. 28,000 - Rs. 44,000",
    materialsUsed: ["Waterproofing compound", "Crack repair material", "Moisture-resistant primer", "Exterior-grade finish paint"],
    beforeImages: [{ src: "/images/projects/waterproofing-before-1.jpg", alt: "Damp wall before waterproofing", tone: "clay" }],
    afterImages: [{ src: "/images/projects/waterproofing-after-1.jpg", alt: "Prepared wall after waterproofing", tone: "sage" }],
    galleryImages: [
      { src: "/images/projects/waterproofing-gallery-1.jpg", alt: "Surface preparation for waterproofing", tone: "clay" },
      { src: "/images/projects/waterproofing-gallery-2.jpg", alt: "Waterproof coating application", tone: "sage" },
      { src: "/images/projects/waterproofing-gallery-3.jpg", alt: "Repaint-ready wall finish", tone: "mist" },
    ],
    featured: true,
    tags: ["Waterproofing", "Monsoon", "Repair"],
    relatedServiceSlug: "waterproofing",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project_texture_feature_wall",
    title: "Textured Feature Wall Upgrade",
    slug: "textured-feature-wall-upgrade",
    city: "Indira Nagar",
    serviceType: "Texture Painting",
    propertyType: "Apartment",
    shortDescription: "Sample feature-wall presentation showing how a plain TV wall can become a subtle textured backdrop.",
    problem: "The living room lacked a focal point and the customer wanted a premium look without heavy carpentry.",
    solution:
      "Wallora suggested a muted texture finish, prepared the base wall, and completed a controlled pattern application.",
    resultSummary: "The TV wall gained depth and the room felt more designed without changing the furniture layout.",
    timeline: "2 days",
    areaSize: 140,
    budgetRange: "Rs. 18,000 - Rs. 26,000",
    materialsUsed: ["Texture base coat", "Pattern finishing material", "Masking tape", "Protective sheet covering"],
    beforeImages: [{ src: "/images/projects/texture-before-1.jpg", alt: "Plain TV wall before texture", tone: "mist" }],
    afterImages: [{ src: "/images/projects/texture-after-1.jpg", alt: "Finished textured TV wall", tone: "ink" }],
    galleryImages: [
      { src: "/images/projects/texture-gallery-1.jpg", alt: "Texture close-up", tone: "ink" },
      { src: "/images/projects/texture-gallery-2.jpg", alt: "Living room feature wall", tone: "warm" },
      { src: "/images/projects/texture-gallery-3.jpg", alt: "Masked texture work area", tone: "mist" },
    ],
    featured: true,
    tags: ["Texture", "Feature Wall", "Living Room"],
    relatedServiceSlug: "texture-painting",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project_wallpaper_kids_room",
    title: "Kids Room Wallpaper Story",
    slug: "kids-room-wallpaper-story",
    city: "Lucknow",
    serviceType: "Wallpaper",
    propertyType: "Apartment",
    shortDescription: "Sample kids room wallpaper concept with neat edge finishing and a quick, low-mess turnaround.",
    problem: "The room felt bare and the family wanted a non-messy design upgrade before school reopened.",
    solution:
      "The team checked wall smoothness, installed a selected wallpaper pattern, and finished edges around switches and corners.",
    resultSummary: "The room became brighter and more personal in a single working day.",
    timeline: "1 day",
    areaSize: 110,
    budgetRange: "Rs. 14,000 - Rs. 22,000",
    materialsUsed: ["Designer wallpaper roll", "Wallpaper adhesive", "Surface primer touch-up", "Edge finishing tools"],
    beforeImages: [{ src: "/images/projects/wallpaper-before-1.jpg", alt: "Plain kids room wall before wallpaper", tone: "mist" }],
    afterImages: [{ src: "/images/projects/wallpaper-after-1.jpg", alt: "Kids room wallpaper after installation", tone: "warm" }],
    galleryImages: [
      { src: "/images/projects/wallpaper-gallery-1.jpg", alt: "Wallpaper pattern detail", tone: "warm" },
      { src: "/images/projects/wallpaper-gallery-2.jpg", alt: "Finished kids room feature wall", tone: "sage" },
      { src: "/images/projects/wallpaper-gallery-3.jpg", alt: "Wallpaper edge finish", tone: "mist" },
    ],
    featured: false,
    tags: ["Wallpaper", "Kids Room", "Quick Upgrade"],
    relatedServiceSlug: "wallpaper",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project_wood_polish_restore",
    title: "Teak Door Polish Restoration",
    slug: "teak-door-polish-restoration",
    city: "Kanpur Road",
    serviceType: "Wood Polish",
    propertyType: "Villa",
    shortDescription: "Sample wood polish presentation for teak doors needing a warmer, richer finish.",
    problem: "The doors had faded unevenly and the entrance no longer matched the premium interior finish.",
    solution:
      "Wallora planned sanding, stain balancing, and protective polish coats with drying time between applications.",
    resultSummary: "The entrance doors regained a richer tone and smoother finish.",
    timeline: "3 days",
    areaSize: 180,
    budgetRange: "Rs. 32,000 - Rs. 48,000",
    materialsUsed: ["Sanding sheets", "Wood stain", "Melamine polish", "Protective masking"],
    beforeImages: [{ src: "/images/projects/wood-before-1.jpg", alt: "Faded teak door before polish", tone: "clay" }],
    afterImages: [{ src: "/images/projects/wood-after-1.jpg", alt: "Restored teak door after polish", tone: "warm" }],
    galleryImages: [
      { src: "/images/projects/wood-gallery-1.jpg", alt: "Sanded teak surface", tone: "clay" },
      { src: "/images/projects/wood-gallery-2.jpg", alt: "Wood polish finish detail", tone: "warm" },
      { src: "/images/projects/wood-gallery-3.jpg", alt: "Finished villa entrance door", tone: "ink" },
    ],
    featured: false,
    tags: ["Wood Polish", "Villa", "Restoration"],
    relatedServiceSlug: "wood-polish",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "project_false_ceiling_office",
    title: "Compact Office Ceiling Finish",
    slug: "compact-office-ceiling-finish",
    city: "Barabanki",
    serviceType: "False Ceiling",
    propertyType: "Office",
    shortDescription: "Sample compact office ceiling plan with cleaner finishing and lighting-ready scope.",
    problem: "The workspace ceiling looked unfinished and exposed wiring made the meeting room feel temporary.",
    solution:
      "The team planned a simple ceiling layout, finishing allowance, and lighting-ready points for a cleaner work setting.",
    resultSummary: "The meeting room looked more composed and client-ready within a week.",
    timeline: "6 days",
    areaSize: 320,
    budgetRange: "Rs. 62,000 - Rs. 84,000",
    materialsUsed: ["Gypsum board", "GI framing", "Jointing compound", "Primer and ceiling paint"],
    beforeImages: [{ src: "/images/projects/ceiling-before-1.jpg", alt: "Office ceiling before false ceiling", tone: "mist" }],
    afterImages: [{ src: "/images/projects/ceiling-after-1.jpg", alt: "Finished office false ceiling", tone: "sage" }],
    galleryImages: [
      { src: "/images/projects/ceiling-gallery-1.jpg", alt: "Ceiling framing work", tone: "mist" },
      { src: "/images/projects/ceiling-gallery-2.jpg", alt: "Finished office ceiling", tone: "sage" },
      { src: "/images/projects/ceiling-gallery-3.jpg", alt: "Meeting room ceiling finish", tone: "ink" },
    ],
    featured: false,
    tags: ["False Ceiling", "Office", "Interior Finishing"],
    relatedServiceSlug: "false-ceiling",
    status: "completed",
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
];
