import type { Service } from "@/types/service";

export const services: Service[] = [
  {
    id: "interior_painting",
    title: "Interior Painting",
    slug: "interior-painting",
    category: "Painting",
    shortDescription: "Premium interior repainting with surface preparation, primer, and clean finishing.",
    description:
      "Refresh bedrooms, living rooms, kitchens, and full homes with a managed interior painting process designed for Indian homes.",
    startingPrice: 24,
    timeline: "2-5 days",
    idealFor: ["Full home repainting", "Rental refreshes", "Bedroom and living room makeovers"],
    includedServices: ["Wall condition check", "Furniture and floor masking", "Surface preparation", "Primer and paint application", "Basic site cleanup"],
    processSteps: ["Requirement review", "Site measurement", "Surface preparation", "Paint application", "Final inspection"],
    benefits: ["Cleaner execution", "Transparent scope", "Finish guidance", "Low-disruption planning"],
    faqs: [
      {
        question: "How long does interior painting take?",
        answer: "Most apartments take 2-5 days depending on area size, surface condition, and selected finish.",
      },
      {
        question: "Is furniture protection included?",
        answer: "Basic masking and floor/furniture protection are included in the planned execution scope.",
      },
    ],
    estimatorServiceType: "interior_painting",
    ctaLabel: "Plan Interior Painting",
    isActive: true,
    sortOrder: 10,
  },
  {
    id: "exterior_painting",
    title: "Exterior Painting",
    slug: "exterior-painting",
    category: "Painting",
    shortDescription: "Weather-resistant exterior painting for houses, villas, and commercial facades.",
    description:
      "Protect and renew exterior walls with preparation-led repainting, weather coat recommendations, and structured handover.",
    startingPrice: 30,
    timeline: "3-7 days",
    idealFor: ["Independent houses", "Villas", "Building facades", "Weather-worn exterior walls"],
    includedServices: ["Exterior wall cleaning", "Surface readiness check", "Crack filling guidance", "Weather coat application", "Final inspection"],
    processSteps: ["Exterior inspection", "Area measurement", "Surface cleaning", "Paint system application", "Handover review"],
    benefits: ["Better weather resistance", "Improved curb appeal", "Material guidance", "Longer-lasting finish"],
    faqs: [
      {
        question: "Can exterior painting be done during monsoon?",
        answer: "It depends on surface moisture and weather windows. A site check is recommended before scheduling.",
      },
      {
        question: "Do you help choose exterior paint type?",
        answer: "Yes, the team can recommend paint systems based on exposure, wall condition, and budget.",
      },
    ],
    estimatorServiceType: "exterior_painting",
    ctaLabel: "Estimate Exterior Work",
    isActive: true,
    sortOrder: 20,
  },
  {
    id: "texture_painting",
    title: "Texture Painting",
    slug: "texture-painting",
    category: "Design Finishes",
    shortDescription: "Statement walls and designer texture finishes for premium room accents.",
    description:
      "Create depth and visual interest with curated texture finishes for living rooms, bedrooms, reception walls, and feature zones.",
    startingPrice: 85,
    timeline: "1-3 days",
    idealFor: ["Feature walls", "TV unit backdrops", "Bedrooms", "Reception areas"],
    includedServices: ["Design consultation", "Surface preparation", "Texture material application", "Pattern finishing", "Basic masking"],
    processSteps: ["Design selection", "Wall readiness check", "Base preparation", "Texture application", "Finish review"],
    benefits: ["Custom visual character", "Premium wall presence", "Design-led guidance", "Durable finish options"],
    faqs: [
      {
        question: "Can texture painting be done on one wall?",
        answer: "Yes, texture painting is often used for one accent wall or a defined feature area.",
      },
      {
        question: "Does texture cost more than regular painting?",
        answer: "Yes, texture finishes usually cost more because material, pattern work, and finishing time are higher.",
      },
    ],
    estimatorServiceType: "texture_painting",
    ctaLabel: "Explore Texture Estimate",
    isActive: true,
    sortOrder: 30,
  },
  {
    id: "wallpaper",
    title: "Wallpaper",
    slug: "wallpaper",
    category: "Design Finishes",
    shortDescription: "Wallpaper selection and installation for rooms that need quick design impact.",
    description:
      "Upgrade walls with wallpaper installation for bedrooms, kids rooms, living spaces, and commercial display areas.",
    startingPrice: 65,
    timeline: "1-2 days",
    idealFor: ["Accent walls", "Kids rooms", "Rental-friendly upgrades", "Commercial feature walls"],
    includedServices: ["Surface readiness check", "Wallpaper installation", "Edge finishing", "Basic cleanup"],
    processSteps: ["Pattern selection", "Wall inspection", "Surface preparation", "Wallpaper installation", "Edge and bubble check"],
    benefits: ["Fast transformation", "Large design variety", "Neat feature wall finish", "Easy style refresh"],
    faqs: [
      {
        question: "Does wallpaper need a smooth wall?",
        answer: "A smoother wall gives better results. The team checks readiness before installation.",
      },
      {
        question: "Can wallpaper be used in kitchens?",
        answer: "It can be used in selected dry kitchen zones, but moisture and heat exposure must be reviewed first.",
      },
    ],
    estimatorServiceType: "wallpaper",
    ctaLabel: "Estimate Wallpaper Work",
    isActive: true,
    sortOrder: 40,
  },
  {
    id: "waterproofing",
    title: "Waterproofing",
    slug: "waterproofing",
    category: "Protection",
    shortDescription: "Preventive and corrective waterproofing for dampness, seepage, and leakage-prone areas.",
    description:
      "Address water-related surface problems with inspection-led waterproofing for terraces, bathrooms, exterior walls, and damp patches.",
    startingPrice: 55,
    timeline: "2-5 days",
    idealFor: ["Terraces", "Bathrooms", "Damp walls", "Exterior seepage zones"],
    includedServices: ["Leakage area inspection", "Surface preparation", "Waterproofing coat application", "Curing guidance"],
    processSteps: ["Problem inspection", "Moisture source review", "Surface preparation", "Coating application", "Curing and handover"],
    benefits: ["Reduced seepage risk", "Better paint life", "Problem-first diagnosis", "Clear scope before execution"],
    faqs: [
      {
        question: "Is waterproofing required before repainting damp walls?",
        answer: "Yes, painting over damp walls without treating the source usually causes recurring damage.",
      },
      {
        question: "How soon can walls be painted after waterproofing?",
        answer: "It depends on curing time and moisture levels. The execution team confirms this after inspection.",
      },
    ],
    estimatorServiceType: "waterproofing",
    ctaLabel: "Check Waterproofing Cost",
    isActive: true,
    sortOrder: 50,
  },
  {
    id: "wood_polish",
    title: "Wood Polish",
    slug: "wood-polish",
    category: "Wood Finishes",
    shortDescription: "Polish, stain, and protective finishing for doors, frames, furniture, and wooden surfaces.",
    description:
      "Restore and protect wooden surfaces with sanding, polish selection, stain guidance, and controlled finishing.",
    startingPrice: 90,
    timeline: "2-4 days",
    idealFor: ["Doors and frames", "Furniture refinishing", "Wood panels", "Staircase rails"],
    includedServices: ["Wood surface sanding", "Polish or stain application", "Protective finishing", "Basic cleanup"],
    processSteps: ["Surface review", "Finish selection", "Sanding", "Polish application", "Drying and finish inspection"],
    benefits: ["Restored wood appearance", "Better surface protection", "Finish customization", "Improved detail quality"],
    faqs: [
      {
        question: "Can old wooden furniture be polished again?",
        answer: "Yes, most old wooden furniture can be refinished after surface condition review.",
      },
      {
        question: "Does wood polish smell during work?",
        answer: "Some products can have odour during application and drying, so ventilation planning is important.",
      },
    ],
    estimatorServiceType: "wood_polish",
    ctaLabel: "Estimate Wood Polish",
    isActive: true,
    sortOrder: 60,
  },
  {
    id: "false_ceiling",
    title: "False Ceiling",
    slug: "false-ceiling",
    category: "Interior Finishing",
    shortDescription: "False ceiling planning and finishing estimates for modern rooms and commercial interiors.",
    description:
      "Plan ceiling design, material scope, and finishing work for homes, offices, shops, and premium interior upgrades.",
    startingPrice: 115,
    timeline: "3-7 days",
    idealFor: ["Living rooms", "Bedrooms", "Offices", "Retail shops"],
    includedServices: ["Ceiling layout estimate", "Material and labour estimate", "Finishing allowance", "Basic site cleanup"],
    processSteps: ["Requirement review", "Ceiling area measurement", "Design planning", "Material scope estimate", "Execution handover"],
    benefits: ["Cleaner ceiling design", "Lighting integration planning", "Premium room finish", "Better service coordination"],
    faqs: [
      {
        question: "Can lighting be planned with false ceiling?",
        answer: "Yes, lighting points and design intent should be discussed before execution starts.",
      },
      {
        question: "Is false ceiling suitable for small rooms?",
        answer: "It can be, but ceiling height and layout need to be checked before recommending a design.",
      },
    ],
    estimatorServiceType: "false_ceiling",
    ctaLabel: "Plan False Ceiling",
    isActive: true,
    sortOrder: 70,
  },
];
